name: Log Branch Deletion

# on:
#   delete:
#     # This workflow will only run when a branch is deleted
#     # No need to specify 'branches' here as the delete event is only triggered for branches

# jobs:
#   log-deletion:
#     runs-on: ubuntu-latest
#     if: github.event.ref_type == 'branch'

#     steps:
#       - name: Log branch deletion
#         env:
#           BRANCH_REF: ${{ github.event.ref }}
#         run: echo "Branch deleted - $BRANCH_REF"

on:
  delete:
    # This workflow triggers on deletion events (branches and tags).
    # It will only proceed when a branch is deleted (see the condition below).

jobs:
  log-deletion:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'branch'
    env:
      GITHUB_EVENT_REF: ${{ github.event.ref }}

    steps:
      - name: Get branch name and log deletion
        run: |
          BRANCH_NAME="${GITHUB_EVENT_REF}"
          echo "Branch deleted bruh: $BRANCH_NAME"
