name: Log Secrets
on:
  workflow_dispatch:

jobs:
  log-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check Secrets
        run: |
          echo "NEON_PROJECT_ID is set: ${{ secrets.NEON_PROJECT_ID != '' }}"
          echo "NEON_API_KEY is set: ${{ secrets.NEON_API_KEY != '' }}"
